#!/usr/bin/env bash
# scripts/fetch-assets.sh — fetch pinned JS/CSS assets into Resources/
set -euo pipefail

cd "$(dirname "$0")/.."
RES=Resources
HLJS=11.9.0
HLJS_SHA256=837a6fa5b0c736b52bbde2b2b6190f305da3fc9ed41681db5321507057b5c846
MARKED=12.0.2
MERMAID=10.9.1
MODE=${1:-all}

if [[ $# -gt 1 ]] || [[ "$MODE" != all && "$MODE" != highlight ]]; then
  echo "Usage: $0 [highlight]" >&2
  exit 2
fi

mkdir -p "$RES"

checksum_matches() {
  [[ -f "$1" ]] || return 1
  local sum
  sum=$(shasum -a 256 "$1")
  [[ ${sum%% *} == "$HLJS_SHA256" ]]
}

if [[ "$MODE" == highlight ]] && checksum_matches "$RES/highlight.min.js"; then
  echo "Verified $RES/highlight.min.js"
  exit 0
fi

if [[ "$MODE" == all ]]; then
  # marked and mermaid are committed; only highlight.js is fetched on build.
  curl -fsSLo "$RES/marked.min.js" \
    "https://cdn.jsdelivr.net/npm/marked@${MARKED}/marked.min.js"
  curl -fsSLo "$RES/mermaid.min.js" \
    "https://cdn.jsdelivr.net/npm/mermaid@${MERMAID}/dist/mermaid.min.js"
fi

# highlight.js: the browser bundle already includes the common languages.
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
curl -fsSLo "$TMP/highlight.min.js" \
  "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@${HLJS}/build/highlight.min.js"
if ! checksum_matches "$TMP/highlight.min.js"; then
  sum=$(shasum -a 256 "$TMP/highlight.min.js")
  echo "highlight.js SHA-256 mismatch: expected $HLJS_SHA256, got ${sum%% *}" >&2
  exit 1
fi
mv "$TMP/highlight.min.js" "$RES/highlight.min.js"

if [[ "$MODE" == all ]]; then
  # Combined theme: GitHub light + dark, gated by prefers-color-scheme
  LIGHT=$(curl -fsSL "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@${HLJS}/build/styles/github.min.css")
  DARK=$(curl -fsSL "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@${HLJS}/build/styles/github-dark.min.css")
  {
    echo "$LIGHT"
    echo "@media (prefers-color-scheme: dark) {"
    echo "$DARK"
    echo "}"
  } >"$RES/theme.css"

  # Record pins
  cat >"$RES/RESOURCES.md" <<EOF
# Bundled assets

Pinned versions fetched by scripts/fetch-assets.sh. Do not edit bundled JS/CSS by hand.

- marked: ${MARKED}
- highlight.js: ${HLJS} (standard browser bundle)
  - Generated by just build when absent; ignored by Git.
  - SHA-256: ${HLJS_SHA256}
- mermaid: ${MERMAID}
- theme.css: highlight.js github + github-dark, combined via prefers-color-scheme
EOF
fi

echo "Fetched to $RES/"
ls -lh "$RES/"
